require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/todo_entries", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TodoEntry. As you add validations to TodoEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TodoEntry.create! valid_attributes
      get todo_entries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      todo_entry = TodoEntry.create! valid_attributes
      get todo_entry_url(todo_entry)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_todo_entry_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      todo_entry = TodoEntry.create! valid_attributes
      get edit_todo_entry_url(todo_entry)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TodoEntry" do
        expect {
          post todo_entries_url, params: { todo_entry: valid_attributes }
        }.to change(TodoEntry, :count).by(1)
      end

      it "redirects to the created todo_entry" do
        post todo_entries_url, params: { todo_entry: valid_attributes }
        expect(response).to redirect_to(todo_entry_url(TodoEntry.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TodoEntry" do
        expect {
          post todo_entries_url, params: { todo_entry: invalid_attributes }
        }.to change(TodoEntry, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post todo_entries_url, params: { todo_entry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested todo_entry" do
        todo_entry = TodoEntry.create! valid_attributes
        patch todo_entry_url(todo_entry), params: { todo_entry: new_attributes }
        todo_entry.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the todo_entry" do
        todo_entry = TodoEntry.create! valid_attributes
        patch todo_entry_url(todo_entry), params: { todo_entry: new_attributes }
        todo_entry.reload
        expect(response).to redirect_to(todo_entry_url(todo_entry))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        todo_entry = TodoEntry.create! valid_attributes
        patch todo_entry_url(todo_entry), params: { todo_entry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested todo_entry" do
      todo_entry = TodoEntry.create! valid_attributes
      expect {
        delete todo_entry_url(todo_entry)
      }.to change(TodoEntry, :count).by(-1)
    end

    it "redirects to the todo_entries list" do
      todo_entry = TodoEntry.create! valid_attributes
      delete todo_entry_url(todo_entry)
      expect(response).to redirect_to(todo_entries_url)
    end
  end
end
